### ISSUE TITLE
Mimikatz error

### ISSUE THREAD

**Issue by sulaimanbale** [xenoscr/atomiccaldera#12]
https://github.com/mitre/caldera/issues/644

This module was from atomic red team calera - atomiccalera and facing the error. How can i get hashes using mimitkaz while getting this error ?

**Comment by xenoscr** [comment]
I would need much more detail regarding any error to be able to assist you, assuming that it is an Atomic Caldera issue. It is likely that the error, whatever it may be, is with the Atomic Red Team test, perhaps a script/binary that they are calling?

If you can provide more detail and have confirmed the issue is in fact with Atomic Caldera, please open a new issue with, a minimum of:

1. Description of the error.
2. Screenshot and/or copy paste of the error.

Please provide as much detail as possible.
